version: "3.8"
services:
  backend:
    image: "joacobnd/springboot-react-fullstack:16.12.2022.10.49.55"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
