version: "3.8"
services:
  backend:
    image: "joacobnd/springboot-react-fullstack:26.12.2022.18.16.26"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
