version: "3.8"
services:
  backend:
    image: "joacobnd/springboot-react-fullstack:5.12.2022.20.24.30"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
